### ISSUE TITLE
Include p(z) tests in the scripts

### ISSUE THREAD

**Issue by rongpu** [LSSTDESC/PZDC1paper#4]
The current version of the Python scripts only considers metrics on n(z) where only two PDFs are needed, but that would not be enough for p(z) tests. For example, we need individual CDF values evaluated at spec-z's to make QQ plots and calculating the CvM statistic for assessing p(z) quality. Should we rewrite the `EvaluateMetric` class to include both n(z) and p(z) tests, or perhaps make a separate class for p(z) tests? We also need scripts that load the raw p(z) data from different photo-z codes and computes the CDF values. Is it something that `qp` would do? I have script that does this but it only works for EAZY outputs.

**Comment by johannct** [comment]
by the way, there is no indication on where the qp module comes from. I should know probably, but could not easily figure out.

**Comment by rongpu** [comment]
@johannct Here is the link to the Alex's `qp` repository: https://github.com/aimalz/qp, although I'm not sure which branch to use.

**Comment by sschmidt23** [comment]
You should be using the issue/43/survey_mode branch that includes Ensemble distributions:
https://github.com/aimalz/qp/tree/issue/43/survey_mode
There is a bit of discussion on this in the first issue#1 on this repository:
https://github.com/LSSTDESC/PZDC1paper/issues/1

**Comment by aimalz** [comment]
Thank you all for the suggestions for improving [`qp`](https://github.com/aimalz/qp)!  The `qp.Ensemble` class is now part of the `master` branch, so no one will have to muck around in the dev branches anymore.  And, both `qp.PDF` and `qp.Ensemble` classes can now calculate integrals between given limits (which could easily be 0 and the true redshift for each galaxy).  @rongpu Is this is all that's necessary to implement the QQ and CvM metrics in the scripts?

**Comment by rongpu** [comment]
@aimalz Yes, that is all that's needed for QQ and CvM metrics. Thanks!

**Comment by sschmidt23** [comment]
@rongpu, I put a very rudimentary QQplot function up here:
https://github.com/LSSTDESC/PZDC1paper/blob/pz_metrics/metric_scripts/individual_metrics.py
and an example ipynb with only 2000 BPZ p(z)'s (limited because the qp stuff is still pretty slow, so I used a small set for testing) here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/NEW_PIT_QQ_test.ipynb
This was definitely quick and dirty, but I wanted to put it up so that you had how I do things for comparison.  If your code is better, by all means replace this.

**Comment by rongpu** [comment]
@sschmidt23 I modified your NEW_PIT_QQ_test.ipynb notebook and used it on p(z)'s from EAZY, and found that the PIT values are different from what I get using my own codes, thus different QQ plots. In fact, some of the PIT values are larger than 1 (e.g. 1.2).  I'm not sure if it's because I'm using the qp ensemble incorrectly. This ipython notebook shows what I did: 
https://github.com/rongpu/PZDC1PaperScripts/blob/master/my_scripts/PIT_QQ_test.ipynb
And in the same repo there is p(z) data used in the notebook.

**Comment by sschmidt23** [comment]
I found what is causing this: EAZY by default does not output the PDFs on a fixed-delta grid, but instead uses a grid that increases as delta*(1+z).  If you look at lines 68-69 in qp/pdf.py, you'll see that qp tries to normalize each PDF assuming a fixed delta spacing, and thus each of the EAZY PDFs is incorrectly normalized.  @aimalz, would using='histogram' and setting up the delta*(1+z) bins accordingly solve this problem?  I'll test that now.

**Comment by sschmidt23** [comment]
I just checked, it does work when you use using='histogram', the resulting QQ plot looks very similar to the one computed your way, @rongpu.  The only needed change is that qp histogram expects bin edges, not bin centers.

**Comment by aimalz** [comment]
@rongpu There is a very stupid (on my part) bug in `qp` wherein I called `np.linspace` instead of `np.arange` in the `qp.PDF.integrate()` function and somehow never got an error in previous tests.  Thanks a ton for finding it!  A bug fix is now in [this branch](https://github.com/aimalz/qp/tree/pzdc1bugs) and will hopefully make it into the master branch by the end of the week.  EDIT: Ha, no, that was me misreading a line break.  But it was a bug in design and is now fixed anyway.

**Comment by aimalz** [comment]
@sschmidt23 Oh, I now see your comments.  Yes, I'd written it so it worked as long as everything was evenly spaced, but the rest of `qp` doesn't require that, so that really was a bug.

**Comment by sschmidt23** [comment]
Ok, it was ambiguous, as it was not clear in the comments that the grid needed to be regular, and aside from the normalization it looked like it would work with any set of points.  Do you want gridded to be restricted to "fixed delta grid" and histogram to work for "irregular grid"?  If so, a couple more lines in the comments of pdf.py and ensemble.py might make that more clear to the user.

**Comment by aimalz** [comment]
No, you were right!  `qp` is designed to accommodate irregular grids, bins, and quantiles.  There are a few places where I got sloppy (the integration function being the most recent of them) and stopped being consistent.  I'm going to write a few test cases to catch those before an official code release, because I'm sure there are more in there.

**Comment by aimalz** [comment]
@sschmidt23 The bug fix for the KLD on an irregular grid is now in `qp`'s `master` branch.
