### ISSUE TITLE
N(z) vs p(z) metrics

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#5]
As @rongpu mentioned in Issue #4, not all of the metrics were coded up for both p(z) and N(z).  On thinking about a few of these, I couldn't come up with how to implement them for individual p(z).  But, this may be because I am missing something.  

Are there metrics that cannot be computed on the individual p(z)'s?  If so, please discuss below.  And if so, are there any alternative (possibly hand-wavey versions of the same metrics) equivalent metrics that could take their place?

**Comment by aimalz** [comment]
There are some metrics that cannot be coded up for individual p(z)s, namely those that require a comparison between a "true" p(z) and a p(z) estimated by some code, since we do not have the former.  I think this will be a major problem we'll have to address in the paper, that our experimental design cannot answer the question of how accurately/precisely a code producing p(z|data,method/assumptions) estimates an underlying p(z|data).

 That being said, @aimalz @rongpu @janewman-pitt-edu @oferlahav5 \[Does anyone know John Soo's GitHub username?\], I propose we all finalize our subsections of Sec. 4 in [the paper](https://www.overleaf.com/read/bknhbskdmrxq) _this week_ to explicitly outline how each metric is (and is not) to be used in our scripts, i.e. on p(z) relative to z_true, n(z|{p(z)}) vs. n(z|{z_true}), etc. by writing down equations for exactly how it must be implemented in the scripts, whether or not the implementation has been written.  (Yes, I know I'm the most behind on this task, but having a deadline will make me get it done!)  Once all the ideas are out on the table, we can use this space to discuss variants on what's in the paper to try to get at how to quantify the performance of individual p(z)s.  How does that sound?

**Comment by sschmidt23** [comment]
@aimalz if you look at what @rongpu coded up in [individual_metrics.py](https://github.com/LSSTDESC/PZDC1paper/blob/pz_metrics/metric_scripts/individual_metrics.py) you'll see that he compares the distribution of PIT values to a uniform distribution for all of KS, CvM, and AD.  While this may not be a true comparison of "true p(z)" and p(z) estimate, it does test something different from the comparison of stacked p(z) and "true N(z)".  So, I think we should include these, of course describing exactly what do in section 4.

And I agree that we should try to finalize the writing in section 4 ASAP.

What do others think?
(also, I just looked at the Github users for LSSTDESC, I do not see John Soo among them), though you did forget to tag @morriscb and @protopotato

**Comment by aimalz** [comment]
Re: PIT vs. uniform, that's what I meant by "metrics on p(z) relative to z_true, n(z|{p(z)}) vs. n(z|{z_true}), etc."  Our ideas of "etc." here merit careful documentation because, I think, some have never been done before.

Sorry for forgetting to tag folks who aren't signed up for that section on Overleaf; anyone who's reading this, feel free to claim a subsection of Sec. 4 and just write it!

**Comment by janewman-pitt-edu** [comment]
I don't understand what a "true p(z)" can be.  The metrics for comparison of CDFs evaluated at z_true to a uniform distribution do enable tests of whether individual p(z)'s fulfill the statistical definition, so I absolutely wouldn't want to lose them.

**Comment by janewman-pitt-edu** [comment]
There is zero chance I can do anything significant in the next couple of weeks, due to the start of classes and the DOE proposal deadline.

**Comment by janewman-pitt-edu** [comment]
I don't understand the statement that:

_our experimental design cannot answer the question of how accurately/precisely a code producing p(z|data,method/assumptions) estimates an underlying p(z|data)._

for a given method/assumptions we absolutely can test whether the p(z | data) fulfills the statistical definition of a PDF.  That is the key goal for PZ DC1.

**Comment by aimalz** [comment]
@janewman-pitt-edu Sorry, I didn't mean to be confusing.  The tests we're doing are not tests of whether the p(z)s produced by each code are _accurate_ in that we are not recovering some underlying p(z|data) from which the dataset was actually generated.  Instead, we are verifying that they are indeed probability distributions at all.  This is a question of, "Are these p(z) codes doing what they say they do?" rather than "How well do these codes do what they say they do?"  I don't think this means we shouldn't calculate these metrics!  I just think we need to be clear about what these metrics get at and what information we cannot probe.

**Comment by aimalz** [comment]
I think we can safely close this issue now that the paper's been written.
